name: Deploying
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode -o certificate.p12
          security create-keychain -p "1234" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "1234" build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "1234" build.keychain
          /usr/bin/codesign --force -s VQ5S8853A4 ./muredan.ios.xcodeproj -v
      - name: Retrieve Dependencies Cache
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: CocoaPod Install
        run: pod install
      - name: Archiving project
        run: ./.github/scripts/archive_app.sh
        # uses: sersoft-gmbh/xcodebuild-action@v2
        # with:
        #   action: archive
        #   workspace: muredan.ios.xcworkspace
        #   scheme: muredan.ios
        #   sdk: iphoneos
        #   build-settings: >
        #     -archivePath build/muredan.ios.xcarchive
        #   derived-data-path: build/derivedData
        #   destination: generic/platform=iOS
      # - name: "Archive"
      #   uses: devbotsxyz/xcode-archive@v1
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/build.keychain
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
