name: Deploying
on:
  push:
    branches:
      - main
env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: [self-hosted, ios-deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Retrieve Dependencies Cache
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Locale
        run: locale
      - name: CocoaPod Install
        run: pod install
      - name: Archiving project
        run: |
        locale
        ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh