name: Deploying
on:
 push:
   branches:
     - main
env:
 LANG: "en_US.UTF-8"
 LANGUAGE: "en_US.UTF-8"
 LC_ALL: "en_US.UTF-8"
jobs:
 deploy:
   name: Deploying to Testflight
   runs-on: macos-latest
   timeout-minutes: 30
   steps:
     - name: Checkout repository
       uses: actions/checkout@v1
     - name: Certificates
        env:   
         BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
         P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
         BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: ./.github/scripts/decrypt_secrets.sh
       uses: |
         ./.github/scripts/decrypt_secrets.sh
     - name: Retrieve Dependencies Cache
       uses: actions/cache@v3
       with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
           ${{ runner.os }}-pods-
     - name: Locale
       run: locale
     - name: CocoaPod Install
       run: pod install
     - name: Archiving project
       run: |
         caffeinate ./.github/scripts/archive_app.sh
     - name: Exporting .ipa
       run: ./.github/scripts/export_ipa.sh
     - name: Publishing app
       if: success()
       env:
         APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
         APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
       run: ./.github/scripts/publish_testflight.sh
